server:
  port: 8080

spring:
  application:
    name: customer_management

  datasource:
    url: jdbc:h2:mem:testdb # H2 in-memory veritaban?
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    # E?er H2 dosya tabanl? veritaban? kullanmak istiyorsan?z, 'jdbc:h2:file:~/testdb' gibi bir URL kullanabilirsiniz.

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: true

  # H2 konsolunu aktif hale getirmek için a?a??daki ayar? da ekleyebilirsin:
  h2:
    console:
      enabled: true
      path: /h2-console
